# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine
WORKDIR /app

# Copy source and ensure assets directory exists for build
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src
RUN mkdir -p src/assets

# Install dependencies and build
RUN npm install --ignore-scripts && npm run build

# Start the MCP server
ENTRYPOINT ["node", "dist/index.js"]
